[package]
name = "rust"
version = "0.1.0"
authors = ["xi.nie <xi.nie@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "leetcode"
path = "./src/leetcode.rs"

[dependencies]
regex = "1"
